parameters:
    pimee_catalog_rule.applier.product.updater.class: PimEnterprise\Bundle\ClassificationRuleBundle\Engine\ProductRuleApplier\ProductsUpdater

services:
    pimee_catalog_rule.applier.product.updater:
        class: %pimee_catalog_rule.applier.product.updater.class%
        arguments:
            - '@pim_catalog.updater.product_property_setter'
            - '@pim_catalog.updater.product_property_copier'
            - '@pim_catalog.updater.product_template'
            - '@pim_catalog.repository.category'
