parameters:
    pimee_classification_rule.model.add_category_action.class: PimEnterprise\Bundle\ClassificationRuleBundle\Model\ProductAddCategoryAction
    pimee_classification_rule.model.set_category_action.class: PimEnterprise\Bundle\ClassificationRuleBundle\Model\ProductSetCategoryAction
