services:
    pimee_classification_rule.denormalizer.product_rule.unclassify_action:
        class: %pimee_catalog_rule.denormalizer.product_rule.action.class%
        arguments:
            - %pimee_classification_rule.model.unclassify_action.class%
            - 'unclassify'
        tags:
            - { name: 'pimee_catalog_rule.denormalizer.product_rule' }
